/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is regenerated by Next.js on `next dev` / `next build`.
// It is committed as a stub so the editor and typechecker work before the
// first build. See https://nextjs.org/docs/basic-features/typescript
